language: python

python:
  - 3.4
  - 3.3
  - 2.7

env:
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.7,<1.8"
  - DJANGO="Django>=1.6,<1.7"

install:
  - pip install -U coverage coveralls django-etc $DJANGO

script: coverage run -a --source=siteflags siteflags/runtests.py

matrix:

  include:
   - python: 3.4
     env: DJANGO="Django>=1.8,<1.9"
   - python: 3.4
     env: DJANGO="Django>=1.7,<1.8"

after_success:
  coveralls
